### ISSUE TITLE
Ranges do not support ::has?

### ISSUE THREAD

**Issue by marcellerusu** [marcellerusu/coil-lang#10]
# Issue Description
```
(0..10)::has?(2)::log()
```
should return `true`
but currently throws the following error

```
error: Uncaught TypeError: Cannot read properties of undefined (reading 'has?')
return this['[]'].call(this, Collection)['has?']['call'](this, val);})
                                        ^
    at ERange.has__q (file:///Users/marcelrusu/Documents/Projects/coil-lang/compiler/example.js:679:41)
    at file:///Users/marcelrusu/Documents/Projects/coil-lang/compiler/example.js:1451:62
```

There are 5 different types of Ranges to make the implementation of them simple. They should all have the same solution, if not be sure to let me know as we might need to rethink this.

# Context on ::has?

::has? is what I'm calling a protocol method for the protocol `Collection`, see `impl Collection for Set = ...` for an example of how it's implemented for Sets. Now there are more methods in `Collection` than just ::has?, but coil doesn't have a problem with implementing a protocol halfway, so for now let's just implement has? and see how that goes.

# Context on ranges

all ranges implement the 'Call' protocol, this allows you to do the following `(0..10)::call(2) == true`, let's utilize this when implementing '::has?'

# Task

Implement ::has? for all 5 ranges, start with `ERange` and they should all have the same implementation. If that's not the case, let me know.

**Comment by marcellerusu** [comment]
The different types of ranges are the following

```
IRange // "inclusive range".. eg. 0..=10
ERange // "exclusive range" .. eg. 0..10
IRangeNoMin // "inclusive range without a minimum .. eg. (..=0) - all negative numbers including 0
ERangeNoMin // "exclusive range without a minimum .. eg. (..0) - all negative numbers excluding 0
ERangeNoMax // "exclusive range without a max .. eg. (0..) // all positive numbers including 0
```
